---
# tasks file for rpi_network
#
- name: '[main] Include tasks from dependencies.yml'
  include_tasks: dependencies.yml
  tags: [ 'rpi_network', 'rpi_network_dependencies' ]

- name: '[main] Include tasks from nm.yml: set up /etc/NetworkManager/system-connections'
  include_tasks: nm.yml
  when: rpi_network_manager
  tags: [ 'rpi_network', 'rpi_network_manager' ]

- name: '[main] Include tasks from legacy.yml: set up /etc/network/interfaces'
  include_tasks: legacy.yml
  when: rpi_network_legacy
  tags: [ 'rpi_network', 'rpi_network_legacy' ]

- name: '[main] Include tasks from wpa_supplicant.yml'
  include_tasks: wpa_supplicant.yml
  when: rpi_network_wireless
  tags: [ 'rpi_network', 'rpi_network_wireless' ]

- meta: flush_handlers
  tags:
  - rpi_network
  - rpi_network_legacy
  - rpi_network_manager
  - rpi_network_wireless
